### ISSUE TITLE
error in lab with sinon not being defined

### ISSUE THREAD

**Issue by Enoch2k2** [learn-co-curriculum/js-advanced-first-class-functions-practice-lab#1]
@gj 

Just had a screen share with a student that was getting an error with sinon not being defined.

I did come up with a fix. Adding this script in the index.html

```
<script src="node_modules/sinon/pkg/sinon-2.4.1.js"></script>
```

It should be below the script
`<script src="node_modules/chai/chai.js"></script>`

**Comment by gj** [comment]
Fixed in https://github.com/learn-co-curriculum/js-advanced-first-class-functions-practice-lab/commit/7667c63b3ce2ee0be7645f72dc22b7c9d6ecab66.

Thanks @Enoch2k2 !

cc: @JeffKatzy
